import { marked } from "marked";
import hljs from "highlight.js";
import DOMPurify from "dompurify";

// Import a highlight.js theme (GitHub Dark is great for modern UIs)
import "highlight.js/styles/github-dark.css";

// Configure Marked to use Highlight.js for code blocks
marked.setOptions({
  breaks: true, // Converts standard \n to <br> for conversational text
  gfm: true, // GitHub Flavored Markdown (tables, task lists)
  highlight: function (code, lang) {
    const language = hljs.getLanguage(lang) ? lang : "plaintext";
    return hljs.highlight(code, { language }).value;
  },
});

export const renderMarkdown = (text) => {
  if (!text) return "";

  // 1. Parse Markdown to HTML
  const rawHtml = marked.parse(text);

  // 2. Sanitize HTML to prevent XSS
  const safeHtml = DOMPurify.sanitize(rawHtml, {
    // Allow basic styles usually generated by highlight.js
    ALLOWED_TAGS: [
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "blockquote",
      "p",
      "a",
      "ul",
      "ol",
      "nl",
      "li",
      "b",
      "i",
      "strong",
      "em",
      "strike",
      "code",
      "hr",
      "br",
      "div",
      "table",
      "thead",
      "caption",
      "tbody",
      "tr",
      "th",
      "td",
      "pre",
      "span",
    ],
    ALLOWED_ATTR: ["href", "name", "target", "class"],
  });

  return safeHtml;
};
